env: dev

api:
  baseurl: {{REPLACE}}
  endpoints:
    - name: {{REPLACE}} # Suffix to add to baseurl
      tables: # If endpoint returns several tables
        - table_a
        - table_b
    - name: {{REPLACE}} # If endpoint returns one table


gcp:
  key_file: {{REPLACE}}
  upload:
    dataset_id: {{REPLACE}}
    bucketname: {{REPLACE}}
    tables: 
      table_a: # Optionally, add table specific config
        # (Optional)
        # partition_col: Date
        # partition_type: MONTH
        # window: 3
        # lag: 1
        # add_updated_at: True