env: dev

api:
  name: yfinance
  tables: 
    stock_history:
      tickers:
        - MSFT
        - GOOGL
        - AAPL
      period: 6mo
  
gcp:
  key_file: data-science-on-gcp-323609-ec18149ed324.json
  upload:
    dataset_id: yfinance_raw
    bucketname: data-science-on-gcp-323609-yfinance-staging
    schema_path: schemas/stock_history.json
    partition_col: Date
    partition_type: MONTH
    window: 3
    lag: 1
    add_updated_at: True