env: dev

api:
  name: yfinance
  tables: 
    stock_history:
      tickers:
        - MSFT
        - GOOGL
        - AAPL
      period: 5d
  
bigquery:
  dest_dataset_id: yfinance_raw
  key_file: data-science-on-gcp-323609-ec18149ed324.json