env: dev

api:
  baseurl: https://fantasy.premierleague.com/api
  endpoints:
    - name: bootstrap-static
      tables: 
        - elements
    - name: fixtures
  
gcp:
  key_file: data-science-on-gcp-323609-78642d80c4ac.json
  upload:
    dataset_id: fpl_raw
    bucketname: fpl-staging
    tables:
      fixtures:
        file_type: json

